
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ph139.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;


public class App {
  final TextPlayer p1;
  final TextPlayer p2;

  public App(TextPlayer p1, TextPlayer p2) {
    this.p1 = p1;
    this.p2 = p2;
  }

  public void doPlacementPhase() throws IOException{
    p1.doPlacementPhase();
    p2.doPlacementPhase();
  }

  public void doAttackingPhase(TextPlayer p1, TextPlayer p2) throws IOException{
    boolean p1Lost = false;
    boolean p2Lost = false;
    while (!p1Lost && !p2Lost) {
      p1.playOneTurn(p2.theBoard, p2.view, "Player " + p2.name + "'s ocean");
      if (p2.theBoard.hasLost()) {
        p2Lost = true;
        break;
      }
      p2.playOneTurn(p1.theBoard, p1.view, "Player " + p1.name + "'s ocean");
      if (p1.theBoard.hasLost()) {
        p1Lost = true;
      }
    }
  }

  public void announceWinner(TextPlayer p1, TextPlayer p2) {
    if (p1.theBoard.hasLost()) {
      System.out.println("Player " + p2.name + " has won!");
    } else {
      System.out.println("Player " + p1.name + " has won!");
    }
  }
  
  public static void main(String[] args) throws IOException{
    Board<Character> b1 = new BattleShipBoard<>(10, 20, 'X');
    Board<Character> b2 = new BattleShipBoard<>(10, 20, 'X');
    AbstractShipFactory<Character> shipFactory = new V1ShipFactory();
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    TextPlayer p1 = new TextPlayer(b1, input, System.out, shipFactory, "A");
    TextPlayer p2 = new TextPlayer(b2, input, System.out, shipFactory, "B");
    App app = new App(p1, p2);
    app.doPlacementPhase();
    app.doAttackingPhase(p1, p2);
    app.announceWinner(p1, p2);
  }
}
