
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ph139.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;


public class App {
  final TextPlayer p1;
  final TextPlayer p2;

  public App(TextPlayer p1, TextPlayer p2) {
    this.p1 = p1;
    this.p2 = p2;
  }

  public void doPlacementPhase() throws IOException{
    p1.doPlacementPhase();
    p2.doPlacementPhase();
  }
  
  public static void main(String[] args) throws IOException{
    Board<Character> b1 = new BattleShipBoard<>(10, 20);
    Board<Character> b2 = new BattleShipBoard<>(10, 20);
    AbstractShipFactory<Character> shipFactory = new V1ShipFactory();
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    TextPlayer p1 = new TextPlayer(b1, input, System.out, shipFactory, "A");
    TextPlayer p2 = new TextPlayer(b2, input, System.out, shipFactory, "B");
    App app = new App(p1, p2);
    app.doPlacementPhase();
  }
}
